# Generated by Django 5.0.1 on 2024-01-28 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stickerstormapi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sticker',
            name='finish_type',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='sticker',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='sticker',
            name='sticker_size',
            field=models.FloatField(),
        ),
    ]
