# Generated by Django 5.0.1 on 2024-01-28 22:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stickerstormapi', '0002_alter_sticker_finish_type_alter_sticker_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sticker',
            name='finish_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stickerstormapi.finish'),
        ),
        migrations.AlterField(
            model_name='sticker',
            name='sticker_size',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stickerstormapi.size'),
        ),
    ]
